name: Build dev image

on:
  workflow_run:
    workflows: ["Test source and upload to S3"]
    types:
      - completed
  workflow_dispatch:

jobs:
  # Try to build the Ersilia Pack
  upload-ersilia-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate failure
        run: exit 1

  # Fallback to BentoML multistage build if Ersilia Pack fails
  upload-bentoml-multistage:
    needs: upload-ersilia-pack
    if: ${{ failure() && needs.upload-ersilia-pack.result == 'failure' }}
    uses: ersilia-os/ersilia-model-workflows/.github/workflows/upload-bentoml.yml@main
    with:
      repo_name: ${{ github.event.repository.name }}
      version: multistage-condapack
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  # Final fallback to legacy build if both pack and multistage fail
  upload-bentoml-legacy:
    needs: [upload-ersilia-pack, upload-bentoml-multistage]
    if: ${{ failure() && needs.upload-ersilia-pack.result == 'failure' && needs.upload-bentoml-multistage.result == 'failure' }}
    uses: ersilia-os/ersilia-model-workflows/.github/workflows/upload-bentoml.yml@main
    with:
      repo_name: ${{ github.event.repository.name }}
      version: legacy
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
